name: '${name}'
version: '${version}'
main: '${main}'
authors:
  - Drakify
api-version: 1.13

commands:
  get-item:
    description: Get an item
    permission: get-item
    aliases: [gi]
  network-permissions:
    description: Update network permissions
    permission: network-permissions
    aliases: [np]