name: '${name}'
version: '${version}'
main: '${main}'

authors:
  - Drak

api-version: 1.13
folia-supported: true

commands:
  get-item:
    description: Get an item
    permission: restored.command.get-item
    aliases: [gi]
  network-permissions:
    description: Update network permissions
    permission: restored.command.network-permissions
    aliases: [np]